[package]
edition.workspace = true
license.workspace = true
name = "jasmine-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
jasmine-protocol = { workspace = true }
jasmine-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
